rem This file is automatically generated by Projects.py.
rem Do not modify this file -- YOUR CHANGES WILL BE ERASED!
set iOSplatform=iPhoneSimulator
set NDKplatform=19
set NDKarmeabi=False
set NDKx86=False
set NDKmips=False
set solutions="usb|Test|Test2|SampleApps|SkyBox|TerrainApps|otl_SDL|Tanks|IndieLibApps|AllLibs"
set projects="USB_x|NDK_MVC|MSC_MVC|iOS_MVC|SDL2|SDL2|SDL2|SDL2|SDL2|SDL2|weber|weberarbaro|tinyxml_x|otlmesher|otlrenderer|otlutils|opentree|otlrenderer_SDL|OpenAL_x|zip_x|Lua_x|giflib_x|rgb2gif_x|whirlgif_x|assimp2_x|assimp3_x|hlsl2glsl_|hlsl2glsl|hlsl2glslfork-master|zlib_x|png_x|jpeg_x|IL_x|ILU_x|Image3|STX|Effects11|Framework3|otl|spine_x|MeshRenderer2|IndieLib_Static|NSGUI|c_01_Alien_BenchMark|a_01_Installing|a_02_IND_Surface|a_03_IND_Image|a_04_IND_Animation|a_05_IND_Font|a_06_Primitives|a_07_IND_Input|a_08_Collisions|a_11_Animated_Tile_Scrolling|a_13_2d_Camera|a_15_Parallax_Scrolling|a_16_IND_Timer|b_01_IND_Surface_Grids|b_02_Blitting_2d_Directly|b_04_Several_ViewPorts|c_02_Rabbits_BenchMark|IndieLib_Animation_Collision|IndieLib_Blend|IndieLib_Fading|IndieLib_FloatingText|IndieLib_ParallaxScroll|IndieLib_TankEnemies|IndieLib_TankEnemiesParallax|IndieLib_TankFollowsMouseFires|IndieLib_Transitions|a_10_IND_Light|b_03_Blitting_3d_Directly|a_14_3d_Camera|a_09_IND_3dMesh|testspine|testspine2|appforest|apptreeview|appforest_SDL|apptreeview_SDL|testotl1|testotl2|Texture|SkyBox|SkyBox2|SimpleTexture|Blending|NatureScene|RGB8|cppnew|ParticleVS|RadeonTerrainDemo|xusb|lsusb|testusb|FW3|2DAnimation|3DAnimation|3DAnimation2|Shape3D"
set platforms=""
set solution=Test
set mainphoneproject=Test
set package=com.test.Test
set domain=""
set androidurl=""
set sdlurl=""
set adt=""
set assimp3version="assimp-3.2"
set ndk="android-ndk-r9d"
set sdl2version=2.0.4
set sdlimage2version=""
set OSXversion=""
set Debianversion=""
set Ubuntuversion=""
set pythonUbuntuversion=""
set pythonDebianversion=""
set pythonOSXversion=""